### ISSUE TITLE
Next.js 大改修計画

### ISSUE THREAD

**Issue by TwoSquirrels** [asanobuturi/asanobuturi.github.io#2]
全部 [Next.js](/vercel/next.js) に書き直す。

Next.js の SSG 機能を GitHub Actions 上で使うことで、
GitHub Pages でのホスティングを持続させる。

(ついでにリファクタリングもする)

**Comment by TwoSquirrels** [comment]
(だれがやるの問題)

**Comment by chakkun1121** [comment]
いま、私がnext.jsの勉強がてら移行してみています。(採用されなくても構いません)
