### ISSUE TITLE
qullしたはずだが更新されなかった

### ISSUE THREAD

**Issue by chakkun1121** [asanobuturi/asanobuturi.github.io#5]
chakkunです。電工の部屋にプラレール改造の解説を追加してpullしたのですが、何故か消えてしまっています。まだgithub初心者なので何起きたのかわかりませんが、分かる人おしえてください。

**Comment by ocean0801** [comment]
本当に疑問なのですが、なぜ人の話を聞かないのですか？完成したら.mdのファイルを渡せと言っているのになぜ渡さずに自分でやろうとするのですか？

こちらが勝手に内部仕様を変更した事や編集方法の伝達が不十分だった事に関してはこちらに非がありますが、内部仕様を変更したことについてはDiscord上で連絡してありますし、これから入るかもわからなかった特殊なあなたに連絡をしなくても不思議ではないはずです。その上、内部仕様を変更したのはあなたがサイトの編集に参加する前であり、編集の仕方を私、ないしは　先輩に聞くべきではなかったのでしょうか。(もっとも、先輩に言っても結局は私に来るでしょうが。)

あと、自分の不手際で一回Organizationに入るのを拒否していて再度招待してもらっている立場なのに、感謝の言葉一言もないのですか？せめて感謝とまでは行かなくても一本連絡ぐらいしたらどうでしょうか。

あとさらに言うと、なぜGitHub上で連絡をするのでしょうか？現役でこのリポジトリに関わっている人は主に私、もしくは[DIV.IJ](https://github.com/DIV-IJ)先輩だけです。なのになぜ公開されている場所でわざわざ連絡をしてくるのでしょうか。メールなどで連絡をして然るべきです。メールをいちいち送信先を指定するのが面倒くさいと言うのは同意しますが、そうせざるを得なくなったのはあなたが原因です。

あともっと言うと、なぜネット上だけで言うのでしょうか？今日部活があったのになぜ私に言わなかったのでしょうか？私の記憶が間違いでなければあなたと会話した記憶があるのですが？

**Comment by ocean0801** [comment]
あともっと言いますけど部誌の内容を変更する場合には一言書くべきではないでしょうか。
